"""
© Copyright 2020 HP Development Company, L.P.
SPDX-License-Identifier: GPL-2.0-only
"""

output_messages = {
    'INFO_ADDING_PATH_TO_INDEX': '%s adding path [%s] to ml-git index',
    'INFO_ADD_REMOTE': 'Add remote repository [%s] for [%s]',
    'INFO_ADD_STORE': 'Add store [%s://%s] with creds from profile [%s]',
    'INFO_ADD_STORE_WITHOUT_PROFILE': 'Add store [%s://%s]',
    'INFO_ALREADY_ARE_IN_A_REPOSITORY': 'You already are in a ml-git repository (%s)',
    'INFO_CHANGING_REMOTE': 'Changing remote from [%s]  to [%s] for  [%s]',
    'INFO_COMMIT_REPO': 'Commit repo[%s] --- file[%s]',
    'INFO_INITIALIZED_PROJECT': 'Initialized empty ml-git repository in %s',
    'INFO_METADATA_INIT': 'Metadata init [%s] @ [%s]',
    'INFO_PULL': 'Pull [%s]',
    'INFO_PROJECT_CREATE': 'Project Created.',
    'INFO_REMOVED_STORE': 'Removed store [%s://%s] from configuration file.',
    'INFO_SUCCESSFULLY_LOAD_FILES': 'Successfully loaded configuration files!',
    'INFO_WITHOUT_NEW_DATA_TO_ADD': 'There is no new data to add',
    'INFO_REMOTE_FSCK': 'remote-fsck -- fixed   : ipld[%d] / blob[%d]',
    'INFO_REMOTE_FSCK_UNFIXED': 'remote-fsck -- unfixed   : ipld[%d] / blob[%d]',
    'INFO_REMOTE_FSCK_TOTAL': 'remote-fsck -- total   : ipld[%d] / blob[%d]',
    'INFO_CONSIDER_USING_THOROUGH_OPTION': '%s missing descriptor files. Consider using the --thorough option.',
    'INFO_MISSING_DESCRIPTOR_WITH_THOROUGH': '%s missing descriptor files. Download: ',
    'INFO_TOTAL_OF_CORRUPTED_FILES': 'Total of corrupted files: %d',
    'INFO_CREATE_TAG_SUCCESSFULL': 'Create Tag Successfull',
    'INFO_EXPORTING_TAG': 'Exporting tag [%s] from [%s] to [%s]',
    'INFO_FILE_PERMISSIONS_CHANGED': 'The permissions for %s have been changed.',
    'INFO_CHECKOUT_IN_BARE_MODE_DONE': 'Checkout in bare mode done.',
    'INFO_STORED_FILE_IN_BUCKET': 'Put - stored [%s] in bucket [%s] with key [%s]-[%s]',
    'INFO_METADATA_GET': 'Metadata GET %s',
    'INFO_STARTING_INTEGRITY_CHECK': 'Starting integrity check on [%s]',
    'INFO_GETTING_FILE_FROM_INDEX': 'Getting file [%s] from local index',
    'INFO_NO_BLOBS_TO_PUSH': 'No blobs to push at this time',
    'INFO_PARANOID_MODE_IS_ACTIVE': 'Paranoid mode is active - Downloading files: ',
    'INFO_FIXING_CORRUPTED_FILES': 'Fixing corrupted files in remote store',
    'INFO_COMMIT_BEFORE_GET': 'Please, commit your changes before the get. You can also use the '
                              '--force option to discard these changes. See \'ml-git --help\'.',
    'INFO_NO_FILES_TO_COMMIT': 'No files to commit for [%s]',
    'INFO_ASSOCIATE_ENTITIES': 'Associate %s [%s]-[%s] to the %s',
    'INFO_STATUS_OF_INDEX': '%s: status of ml-git index for [%s]',
    'INFO_NO_HEAD': 'No HEAD for [%s]',
    'INFO_INITIALIZING_RELATED_DOWNLOAD': 'Initializing related %s download',
    'INFO_ALREADY_AT_TAG': 'already at tag [%s]',
    'INFO_INITIALIZING_RESET': 'Initializing reset [%s] [%s] of commit.',
    'INFO_SPEC_WITHOUT_MUTABILITY': 'The spec does not have the \'mutability\' property set. Default: strict.',
    'INFO_CREATE_COMMAND_ABORTED': 'Create command aborted!',
    'INFO_INITIALIZING_WITH_GLOBAL_SETTINGS': 'Initializing the project with global settings',

    'INFO_WITHOUT_GLOBAL_CONFIG': 'You are not in an initialized ml-git repository and do not have a global configuration.',
    'ERROR_REPOSITORY_NOT_FOUND': 'No repositories found, verify your configurations!',
    'ERROR_AMOUNT_SMALLER_THAN_GROUP_SIZE': 'The amount parameter should be smaller than the group size.',
    'ERROR_ANY_ENTITY_BEING_MANAGED': 'You don\'t have any entity being managed.',
    'ERROR_SIZE_SMALLER_THAN_LIST_SIZE': 'The group size parameter should be smaller than the file list size.',
    'ERROR_START_SMALLER_THAN_STOP': 'The start parameter should be smaller than the stop.',
    'ERROR_START_GREATER_THAN_ZERO': 'The start parameter should be greater than or equal to zero.',
    'ERROR_STEP_SMALLER_THAN_STOP': 'The step parameter should be smaller than the stop.',
    'ERROR_STOP_SMALLER_THAN_LIST_SIZE': 'The stop parameter should be smaller than or equal to the file list size.',
    'ERROR_AMOUNT_SMALLER_THAN_FREQUENCY': 'The amount parameter should be smaller than the frequency.',
    'ERROR_FREQUENCY_SMALLER_THAN_LIST_SIZE': 'The frequency  parameter should be smaller than the file list size.',
    'ERROR_FREQUENCY_GREATER_THAN_ZERO': 'The frequency  parameter should be greater than zero.',
    'ERROR_GROUP_SIZE_GREATER_THAN_ZERO': 'The group size parameter should be greater than zero.',
    'ERROR_AMOUNT_GRATER_THAN_ZERO': 'The amount parameter should be greater than zero.',

    'ERROR_MUTABILITY_CANNOT_BE_CHANGED': 'Spec mutability cannot be changed.',
    'ERROR_AWS_KEY_NOT_EXIST': 'The AWS Access Key Id you provided does not exist in our records.',
    'ERROR_CONFIG_PROFILE_NOT_FOUND': 'The config profile (%s) could not be found',
    'ERROR_NO_CURRENT_TAG': 'No current tag for [%s]. commit first.',
    'ERROR_TAG_ALERADY_EXISTS': 'tag \'%s\' already exists',
    'ERROR_CHUNCK_CORRUPTION_DETECTED': 'Corruption detected for chunk [%s] - got [%s]',
    'ERROR_ADD_REMOTE_FIRST': 'Unable to find remote repository. Add the remote first.',
    'ERROR_CHECK_REPOSITORY': 'Unable to find %s. Check the remote repository used.',
    'ERROR_NOT_IN_AN_INITIALIZED_REPOSITORY': 'You are not in an initialized ml-git repository.',
    'ERROR_PATH_ALREADY_EXISTS': 'The path [%s] already exists and is not an empty directory.',
    'ERROR_REQUIRE_POSITIVE_INTEGERS': 'The %s: requires positive integer values.',
    'ERROR_WRTIE_PERMISSION': 'Permission denied. You need write permission to initialize ml-git in this directory.',
    'ERROR_ENTITY_NOT_INITALIZED': 'The %s hasn\'t been initialized.',
    'ERROR_PATH_NOT_EMPTY': 'The path [%s] is not an empty directory. Consider using --folder to create an empty folder.',
    'ERROR_COULD_NOT_READ_FROM_REPOSITORY': 'Could not read from remote repository.',
    'ERROR_PERMISSION_DENIED_IN_FOLDER': 'Permission denied in folder %s',
    'ERROR_FATAL_DOWNLOADING': 'Fatal downloading error [%s]',
    'ERROR_MUTABILITY_CANNOT_BE_STRICT': 'You cannot use this command for this entity because mutability cannot be strict.',
    'ERROR_FILE_NOT_FOUND': 'File %s not found',
    'ERROR_PATH_NOT_FOUND': 'Path %s not found',
    'ERROR_UNABLE_TO_CONNECT_TO_THE_AZURE_STORAGE': 'Unable to connect to the Azure storage.',
    'ERROR_AZURE_CRENDETIALS_NOT_FOUND': 'Azure credentials could not be found. See the ml-git documentation for how to configure.',
    'ERROR_DRIVE_PATH_NOT_FOUND': 'Drive path [%s] not found.',
    'ERROR_KEY_PATH_ALREADY_EXISTS_IN_DRIVE': 'Key path [%s] already exists in drive path [%s].',
    'ERROR_FILE_COULD_NOT_BE_UPLOADED': 'The file could not be uploaded: [%s]',
    'ERROR_AUTHENTICATION_FAILED': 'Authentication failed',
    'ERROR_BUCKET_NOT_EXIST': 'This bucket does not exist -- [%s]',
    'ERROR_BUCKET_NOT_CONFIGURED_WITH_VERSIONING': 'Put - bucket [%s] not configured with Versioning',
    'ERROR_BUCKET_NAME_CONFLICTING': 'Exception creating store -- bucket name conflicting between config file [%s] and spec file [%s]',
    'ERROR_GIT_AUTHENTICATION_FAILED': 'Authentication failed for git remote',
    'ERROR_ON_PUSH_METADATA': 'Error on push metadata to git repository. Please update your mlgit project!',
    'ERROR_METADATA_MANAGER': 'Metadata Manager: %s ',
    'ERROR_INVALID_ML_GIT_REPOSITORY': 'Invalid ml-git repository',
    'ERROR_THERE_IS_NO_COMMIT_TO_GO_BACK': 'There is no commit to go back. Do at least two commits.',
    'ERROR_NO_LOG_FOUND_FOR_ENTITY': 'No log found for entity [%s]',
    'ERROR_UNKNOWN_DATA_STORE_TYPE': 'Unknown data store type [%s], choose one of these %s.',
    'ERROR_YOU_ARE_IN_INITIALIZED_PROJECT': 'You are in initialized ml-git project.',
    'ERROR_WRONG_MINIMAL_CONFIGURATION_FILES': 'Wrong minimal configuration files!',
    'ERROR_NEED_PASS_SEED_ATTRIBUTE': 'It is necessary to pass the attribute \'seed\' in \'sampling\'. '
                                      'Example: {\'group\': \'1:2\', \'seed\': \'10\'}.',
    'ERROR_INVALID_TYPE_OF_SAMPLING': 'To use the sampling option, you must pass a valid type of sampling (group, random or range).',
    'ERROR_INVALID_BATCH_SIZE_VALUE': 'The batch size value is invalid in the config file for the [%s] key',
    'ERROR_CHUNK_FOUND_IN_WRONG_DIRECTORY': 'Chunk found in wrong directory. Expected [%s]. Found [%s]',
    'ERROR_ADDING_DIR': 'Error adding dir [%s] -- [%s]',
    'ERROR_NO_STORE_FOR': 'No store for [%s]',
    'ERROR_FATAL_PUSH_ERROR': 'fatal push error',
    'ERROR_FATAL_DELETE_ERROR': 'Fatal delete error [%s]',
    'ERROR_IT_WAS_NOT_POSSIBLE_TO_DELETE_ALL_FILES': 'It was not possible to delete all files',
    'ERROR_DOWNLOADING_IPLD': 'Error download ipld [%s]',
    'ERROR_DOWNLOADING_BLOB': 'Error download blob [%s]',
    'ERROR_NO_SPEC_FILE_FOUND': 'No spec file found. You need to initialize an entity (dataset|model|label) first',
    'ERROR_TO_FETCH_IPLD': 'Error to fetch ipld -- [%s]',
    'ERROR_TO_FETCH_FILE': 'Error to fetch file -- [%s]',
    'ERROR_TO_FETCH_BLOB': 'Error to fetch blob -- [%s]',
    'ERROR_TO_FSCK_IPLD': 'Error to fsck ipld -- [%s]',
    'ERROR_TO_FSCK_BLOB': 'Error to fsck blob -- [%s]',
    'ERROR_TO_FSCK_FILE': 'Error to fsck file -- [%s]',
    'ERROR_BLOB_NOT_FOUND': 'Blob [%s] not found. exiting...',
    'ERROR_ADDING_INTO_CACHE_DIR': '\n Error adding into cache dir [%s] -- [%s]',
    'ERROR_ADDING_INTO_WORKSPACE': 'Error adding into workspace dir [%s] -- [%s]',
    'ERROR_LOCAL_CHANGES_WOULD_BE_DISCARDED': 'Your local changes to the following files would be discarded:',
    'ERROR_TO_EXPORT_FILES': 'Error to export files -- [%s]',
    'ERROR_INVALID_IPLD': 'Invalid IPLD [%s]',
    'ERROR_INVALID_MUTABILITY_TYPE': 'Invalid mutability type',
    'ERROR_TAG_ALREADY_EXISTS': 'Tag [%s] already exists in the ml-git repository.\n  '
                                'Consider using --bumpversion parameter to increment the version number for your [%s].',
    'ERROR_TAG_ALREADY_EXISTS_VERSION_NUMBER': 'Tag [%s] already exists in the ml-git repository.\n  '
                                               'Consider using --bumpversion parameter to increment the version number for your [%s].',
    'ERROR_ENTITY_NAME_PASSED_WRONG': 'The entity name passed it\'s wrong. Please check again',
    'ERROR_MUST_PLACE_AT_LEAST_ONE_CATEGORY': 'You must place at least one category in the entity .spec file',
    'ERROR_NO_MANIFEST_FILE_FOUND': 'No manifest file found in [%s]',
    'ERROR_COULD_NOT_FIND_README': 'Could not find file README.md. Entity repository must have README.md file',
    'ERROR_INVALID_DATASET_SPEC': 'invalid dataset spec (Missing name). It should look something like this:\n%s',
    'ERROR_INVALID_SPEC': 'Invalid %s spec in %s.  It should look something like this:\n%s',
    'ERROR_INVALID_CONFIG': '.ml-git/config.yaml invalid.  It should look something like this:\n%s',
    'ERROR_WORKER_FAILURE': 'Worker failure - [%s] -- [%d] attempts',
    'ERROR_NAME_AND_EMAIL_NOT_CONFIGURED': 'Your name and email address need to be configured in git. Please see the commands below:',
    'ERROR_GIT_CONFI_USER_NAME_COMMAND': 'git config --global user.name "Your Name"',
    'ERROR_GIT_CONFI_USER_EMAIL_COMMAND': 'git config --global user.email you@example.com"',
    'ERROR_TAG_NOT_EXIST': 'Tag [%s] does not exist in this repository',
    'ERROR_UNABLE_TO_CHECKOUT': 'Unable to checkout to %s',
    'ERROR_NOT_ENOUGH_SPACE_IN_DISK': 'There is not enough space in the disk. Remove some files and try again.',
    'ERROR_WHILE_CREATING_FILES_INTO_WORKSPACE': 'An error occurred while creating the files into workspace: %s \n.',
    'ERROR_INVALID_ML_GIT_PROJECT': 'Invalid ml-git project!',
    'ERROR_FILE_LIST_EMPTY': 'The file list is empty.',
    'ERROR_RANGE_SAMPLE_USAGE': 'The --range-sample=<start:stop:step> or  --range-sample=<start:stop>: requires positive integer values. '
                                'The stop parameter can be \'all\', \'-1\' or any integer greater than zero',
    'ERROR_SAMPLE_PARAMETER_CANNOT_BE_NONE': 'The sample parameter cannot be None',
    'ERROR_ENTITY_NAME_IS_WRONG': 'The entity name passed is wrong. Please check again',
    'ERROR_INVALID_VERSION': 'Invalid version, could not increment. File:\n     %s',
    'ERROR_NO_NAME_PROVIDED': 'No %s name provided, can\'t increment version.',
    'ERROR_INCREMENTING_VERSION_PLEASE_MANUALLY_EXAMINE': '\nError incrementing version.  Please manually examine this file and make sure'
                                                          ' the version is an integer:\n%s\n',
    'ERROR_CAN_NOT_FIN_SPEC_FILE': 'Can\'t find  spec file to increment version.',
    'ERROR_ENTIT_NOT_EXIST_FOR_RELATED_DOWNLOAD': 'the %s does not exist for related download.',
    'ERROR_INVALID_BUCKET_NAME': 'Invalid bucket name in spec file.\n',
    'ERROR_BUCKET_NAME_NOT_FOUND_IN_CONFIG': 'Bucket name [%s] not found in config.',
    'ERROR_ALREADY_EXISTS_AN_ENTITY': 'An entity with that name already exists.',
    'ERROR_INVALID_VALUE_IN_CONFIG_FILE': 'Invalid value in config file for the [%s] key. '
                                          'This is should be a integer number greater than 0.',
    'ERROR_COULD_NOT_INITIALIZE_METADATA': 'Could not initialize metadata for %s. %s',
    'ERROR_MAKE_CHECKOUT_WITH_SAMPLE': 'You cannot add new data to an entity that is based on a checkout with the --sampling option.',

    'WARN_CORRUPTED_FILES_CANNOT_BE_ADDED': 'The following files cannot be added because they are corrupted:',
    'WARN_FILE_WILL_BE_OVERWRITTEN_IF_COMMITED': 'The file %s already exists in the repository. If you commit, the file will be overwritten.',
    'WARN_STORE_NOT_FOUND_IN_CONFIGURATION': 'Store [%s://%s] not found in configuration file.',
    'WARN_REMOVE_FILES_FROM_STORE_DUE_TO_FAIL': 'Removing %s files from store due to a fail during the push execution.',
    'WARN_WORKER_EXCEPTION': 'Worker exception - [%s] -- retry [%d]',

    "LOG_TAG": "Tag: %s",
    "LOG_TAG_MESSAGE": "Message: %s",
    "LOG_TAG_TOTAL_FILES": "Total of files: %d",
    "LOG_WORKSPACE_SIZE": "Workspace size: %s",
    "LOG_TAG_ADDED_FILES": "Added files [%s]",
    "LOG_TAG_DELETED_FILES": "Deleted files [%s]",
    "LOG_TAG_FILES_SIZE": "Files size: %s",
    "LOG_TAG_AMOUT_OF_FILES": "Amount of files: %s",

    'DEBUG_CONNECT_STORAGE': 'Connect - Storage [%s];',
    'DEBUG_CONNECT_S3_STORAGE': 'Connect - profile [%s] ; region [%s]',
    'DEBUG_CONNECTING_TO_MINIO': 'Connecting to [%s]',
    'DEBUG_CONTAINER_ALREADY_EXISTS': 'Container %s already exists',
    'DEBUG_OBJECT_ALREADY_IN_STORAGE': 'Object [%s] already in %s store',
    'DEBUG_FILE_NOT_IN_LOCAL_REPOSITORY': 'File [%s] not present in local repository',
    'DEBUG_SPECIFIED_BLOB_ALERADY_EXISTS': 'The specified blob [%s] already exists.',
    'DEBUG_LISTING_BLOBS_IN_CONTAINER': '\nListing blobs in container:',
    'DEBUG_AZURE_CONFIGURATIONS_NOT_FIND': 'Azure cli configurations not find.',
    'DEBUG_CHECKSUM_VERIFIED_FOR_CHUNK': 'Checksum verified for chunk [%s]',
    'DEBUG_DOWNLOAD_FILE_FROM_BUCKET': 'Get - downloading [%s], version [%s], from bucket [%s] into file [%s]',
    'DEBUG_DELETING_FILE_FROM_BUCKET': 'Delete - deleting [%s] with version [%s] from bucket [%s]',
    'DEBUG_DOWNLOAD_FILE_WITHOUT_VERSION': 'Get - downloading [%s] from bucket [%s] into file [%s]',
    'DEBUG_DELETING_WITHOUT_VERSION': 'Delete - deleting [%s] from bucket [%s]',
    'DEBUG_STORE_AND_BUCKET': 'Store [%s] ; bucket [%s]',
    'DEBUG_METADATA_CHECK_EXISTENCE': 'Metadata check existence [%s] @ [%s]',
    'DEBUG_PUSH': 'Push [%s]',
    'DEBUG_METADATA_MANAGER_FETCH': ' fetch [%s]',
    'DEBUG_LINK': 'Link from [%s] to [%s]',
    'DEBUG_UPDATE_HASHFS_LOG': 'Update hashfs log',
    'DEBUG_UPDATE_HASHFS_WITH_A_LIST_OF_FILES': 'Update hashfs log with a list of files to keep',
    'DEBUG_UPDATE_LOG_FOR_KEY': 'Update log for key [%s]',
    'DEBUG_LOADING_LOG_FILE': 'Loading log file',
    'DEBUG_MOVING': 'Moving [%s]',
    'DEBUG_CHUNCK_ALERADY_EXIST': 'Chunk [%s]-[%d] already exists',
    'DEBUG_ADD_CHUNK': 'Add chunk [%s]-[%d]',
    'DEBUG_GET_CHUNK': 'Get chunk [%s]-[%d]',
    'DEBUG_BUILDING_STORE_LOG': 'Building the store.log with these added files',
    'DEBUG_BLOB_ALREADY_COMMITED': 'Blob %s already commited',
    'DEBUG_REMOVING_CORRUPTED_FILES': 'Removing %s corrupted files',
    'DEBUG_REMOVING_FILE': 'Removing file [%s]',
    'DEBUG_ADD_FILE_TO_INDEX': 'Add file [%s] to ml-git index',
    'DEBUG_THE_FILE_ISNT_IN_INDEX': 'The file [{}] isn\'t in index',
    'DEBUG_FILE_ALREADY_EXISTS_IN_REPOSITORY': 'File [%s] already exists in ml-git repository',
    'DEBUG_FILE_WAS_MODIFIED': 'File [%s] was modified',
    'DEBUG_PUSH_BLOB_TO_STORAGE': 'push blob [%s] to store',
    'DEBUG_DELETE_BLOB_FROM_STORE': 'Delete blob [%s] from store',
    'DEBUG_GETTING_IPLD_KEY': 'Getting ipld key [%s]',
    'DEBUG_DOWNLOADING_IPLD': 'Downloading ipld [%s]',
    'DEBUG_GETTING_BLOB': 'Getting blob [%s]',
    'DEBUG_DOWNLOADING_BLOB': 'Downloading blob [%s]',
    'DEBUG_REMOVING': 'Removing %s',
    'DEBUG_CHECK_IPLD_IN_STORE': 'check ipld [%s] in store',
    'DEBUG_IPLD_NOT_PRESENT': 'ipld [%s] not present for full verification',
    'DEBUG_FILE_NOT_IN_CACHE': 'File is not in cache',
    'DEBUG_METADATA_PATH': 'Metadata path [%s]',
    'DEBUG_COMMIT_MESSAGE': 'Commit message [%s]',
    'DEBUG_DATASET_PATH': 'Dataset path: %s',
    'DEBUG_GETTING_SUBPATH_FROM_CATEGORIES': 'Getting subpath from categories in specfile [%s]',
    'DEBUG_COMMIT_SPEC': 'Commit spec [%s] to ml-git metadata',
    'DEBUG_NEW_TAG_CREATED': 'New tag created [%s]',
    'DEBUG_CREATE_WORKER_POOL': 'Create a worker pool with [%d] threads & retry strategy of [%d]',
    'DEBUG_WAIT_BEFORE_NEXT_ATTEMPT': 'Wait [%d] before next attempt',
    'DEBUG_WORKER_SUCCESS': 'Worker success at attempt [%d]',
    'DEBUG_SETTING_HEAD': 'Setting head of [%s] to [%s]-[%s]',
    'DEBUG_CHECK_IF_TAG_ALREADY_EXISTS': 'Check if tag already exists',
    'DEBUG_SEARCH_SPEC_FILE': 'search spec file: found [%s]-[%s]',
    'DEBUG_VERSION_INCREMENTED': 'Version incremented to %s.'

}
