"""
© Copyright 2020 HP Development Company, L.P.
SPDX-License-Identifier: GPL-2.0-only
"""

output_messages = {
    'INFO_ADDING_PATH_TO_INDEX': '%s adding path [%s] to ml-git index',
    'INFO_ADD_REMOTE': 'Add remote repository [%s] for [%s]',
    'INFO_ADD_STORE': 'Add store [%s://%s] with creds from profile [%s]',
    'INFO_ALREADY_ARE_IN_A_REPOSITORY': 'You already are in a ml-git repository (%s)',
    'INFO_CHANGING_REMOTE': 'Changing remote from [%s]  to [%s] for  [%s]',
    'INFO_COMMIT_REPO': 'Commit repo[%s] --- file[%s]',
    'INFO_INITIALIZED_PROJECT': 'Initialized empty ml-git repository in %s',
    'INFO_METADATA_INIT': 'Metadata init [%s] @ [%s]',
    'INFO_PULL': 'Pull [%s]',
    'INFO_PROJECT_CREATE': 'Project Created.',
    'INFO_REMOVED_STORE': 'Removed store [s3h://%s] from configuration file.',
    'INFO_SUCCESSFULLY_LOAD_FILES': 'Successfully loaded configuration files!',
    'INFO_WITHOUT_NEW_DATA_TO_ADD': 'There is no new data to add',
    'INFO_REMOTE_FSCK': 'remote-fsck -- fixed   : ipld[%d] / blob[%d]',
    'INFO_CONSIDER_USING_THOROUGH_OPTION': '%s missing descriptor files. Consider using the --thorough option.',
    'INFO_MISSING_DESCRIPTOR_WITH_THOROUGH': '%s missing descriptor files. Download: ',
    'INFO_TOTAL_OF_CORRUPTED_FILES': 'Total of corrupted files: %d',
    'INFO_CREATE_TAG_SUCCESSFULL': 'Create Tag Successfull',
    'INFO_EXPORTING_TAG': 'Exporting tag [%s] from [%s] to [%s]',
    'INFO_FILE_PERMISSIONS_CHANGED': 'The permissions for %s have been changed.',
    'INFO_CHECKOUT_IN_BARE_MODE_DONE': 'Checkout in bare mode done.',
    'INFO_ADD_STORE_WITHOUT_CREDENTIALS': 'INFO - Admin: Add store [%s://%s]',
    'INFO_CREATE_IMPORT': 'The argument `import` is mutually exclusive with argument',
    'INFO_CREATE_IMPORT_UNZIP': 'Unzipping files',
    'INFO_WITHOUT_GLOBAL_CONFIG': 'You are not in an initialized ml-git repository and do not have a global configuration.',
    'INFO_INITIALIZING_WITH_GLOBAL_SETTINGS': 'Initializing the project with global settings',

    'ERROR_ENTITY_WITH_THAT_NAME_ALREADY_EXISTS': 'An entity with that name already exists.',
    'ERROR_AMOUNT_SMALLER_THAN_GROUP_SIZE': 'The amount parameter should be smaller than the group size.',
    'ERROR_ANY_ENTITY_BEING_MANAGED': 'You don\'t have any entity being managed.',
    'ERROR_SIZE_SMALLER_THAN_LIST_SIZE': 'The group size parameter should be smaller than the file list size.',
    'ERROR_START_SMALLER_THAN_STOP': 'The start parameter should be smaller than the stop.',
    'ERROR_STEP_SMALLER_THAN_STOP': 'The step parameter should be smaller than the stop.',
    'ERROR_STOP_SMALLER_THAN_LIST_SIZE': 'The stop parameter should be smaller than or equal to the file list size.',
    'ERROR_AMOUNT_SMALLER_THAN_FREQUENCY': 'The amount parameter should be smaller than the frequency.',
    'ERROR_FREQUENCY_SMALLER_THAN_LIST_SIZE': 'The frequency  parameter should be smaller than the file list size.',
    'ERROR_FREQUENCY_GREATER_THAN_ZERO': 'The frequency  parameter should be greater than zero.',
    'ERROR_GROUP_SIZE_GREATER_THAN_ZERO': 'The group size parameter should be greater than zero.',
    'ERROR_AMOUNT_GRATER_THAN_ZERO': 'The amount parameter should be greater than zero.',

    'ERROR_INVALID_VALUE_FOR_VERSION_NUMBER': 'Error: Invalid value for "--version-number": %s',
    'ERROR_NO_SUCH_OPTION_SAMPLE_TYPE': 'Error: no such option: --sample-type',
    'ERROR_BLOCK_ADD_FROM_SAMPLED_ENTITY': 'You cannot add new data to an entity that is based on a checkout with the --sampling option.',
    'ERROR_COULD_NOT_UPDATE_METADATA': 'Could not update metadata. Check your remote configuration.',
    'ERROR_COULD_NOT_INITIALIZE_METADATA': 'Could not initialize metadata for %s.',
    'ERROR_MUTABILITY_CANNOT_BE_CHANGED': 'Spec mutability cannot be changed.',
    'ERROR_AWS_KEY_NOT_EXIST': 'The AWS Access Key Id you provided does not exist in our records.',
    'ERROR_CONFIG_PROFILE_NOT_FOUND': 'The config profile (%s) could not be found',
    'ERROR_NO_CURRENT_TAG': 'No current tag for [%s]. commit first',
    'ERROR_TAG_ALERADY_EXISTS': 'tag \'%s\' already exists',
    'ERROR_CHUNCK_CORRUPTION_DETECTED': 'Corruption detected for chunk [%s] - got [%s]',
    'ERROR_ADD_REMOTE_FIRST': 'Unable to find remote repository. Add the remote first.',
    'ERROR_CHECK_REPOSITORY': 'Unable to find %s. Check the remote repository used.',
    'ERROR_NOT_IN_AN_INITIALIZED_REPOSITORY': 'You are not in an initialized ml-git repository.',
    'ERROR_PATH_ALREADY_EXISTS': 'The path [%s] already exists and is not an empty directory.',
    'ERROR_REQUIRE_POSITIVE_INTEGERS': 'The %s: requires positive integer values.',
    'ERROR_WRTIE_PERMISSION': 'Permission denied. You need write permission to initialize ml-git in this directory.',
    'ERROR_ENTITY_NOT_INITALIZED': 'The %s hasn\'t been initialized.',
    'ERROR_PATH_NOT_EMPTY': 'The path [%s] is not an empty directory. Consider using --folder to create an empty folder.',
    'ERROR_COULD_NOT_READ_FROM_REPOSITORY': 'Could not read from remote repository.',
    'ERROR_PERMISSION_DENIED_IN_FOLDER': 'Permission denied in folder %s',
    'ERROR_FATAL_DOWNLOADING': 'Fatal downloading error [%s]',
    'ERROR_MUTABILITY_CANNOT_BE_STRICT': 'You cannot use this command for this entity because mutability cannot be strict.',
    'ERROR_FILE_NOT_FOUND': 'File %s not found',
    'ERROR_CREATE_CREDENTIALS_REQUIRED': 'The argument `credentials_path` is required if `import-url` is used.',
    'ERROR_CREATE_INVALID_URL': 'Invalid url: [%s]',

    'WARN_CORRUPTED_FILES_CANNOT_BE_ADDED': 'The following files cannot be added because they are corrupted:',
    'WARN_FILE_WILL_BE_OVERWRITTEN_IF_COMMITED': 'The file %s already exists in the repository. If you commit, the file will be overwritten.',

    "LOG_TAG": "Tag: %s",
    "LOG_TAG_MESSAGE": "Message: %s",
    "LOG_TAG_TOTAL_FILES": "Total of files: %d",
    "LOG_WORKSPACE_SIZE": "Workspace size: %s",
    "LOG_TAG_ADDED_FILES": "Added files [%s]",
    "LOG_TAG_DELETED_FILES": "Deleted files [%s]",
    "LOG_TAG_FILES_SIZE": "Files size: %s",
    "LOG_TAG_AMOUT_OF_FILES": "Amount of files: %s",

}
